import Head from 'next/head'
import Image from 'next/image'
import {RadioButton} from '@/components/radioButton/radioButton'
import CardCategory  from '@/components/cardCategory/cardCategory'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='hi-guys'>
        <CardCategory
          urlLink='https://google.es'
        />
      </main>
    </>
  )
}
